[build]
  publish = "public"  # Make sure Netlify deploys from the 'public' folder
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/calculate-gpa"
  to = "https://gpa-calculator-bpgj.onrender.com/calculate-gpa"
  status = 200
  force = true
